config/routes.rb
Rails.application.routes.draw do

  namespace :api do
     scope :v1  do
       resources :users
         mount_devise_token_auth_for 'User', at: 'auth'
         get "login", to: "/api/v1/login#login"
         get 'next_game', to: "/api/v1/user_login#next_game"
         get 'enrachate_25', to: "/api/v1/user_login#enrachate_25"
         get "enrachate_25_questions", to: "/api/v1/user_login#enrachate_25_questions"
         get "tickets", to: "/api/v1/user_login#tickets"
         post "buy_lottery_ticket", to: "/api/v1/user_login#buy_lottery"
         post "create_enrachate_25_ticket", to: "/api/v1/user_login#create_enrachate_25_ticket"

     end
   end

  resources :gift_cards do
    collection do
      get "create_massive"
      get "generate_massive_cards", to: "gift_cards#generate_massive_cards"
    end
  end

  resources :relation_tira_questions

  resources :relation_enrachate_tiras do
      collection do
          get "close_tira_question"
          get "tiras_for_enrachate", to: "relation_enrachate_tiras#tiras_for_enrachate"
          get "close_question", to: "relation_enrachate_tiras#close_question"
      end
  end

  resources :enrachate_users

  resources :question_enrachates

  resources :tira_enrachates

  resources :enrachates do
    collection do
      get "enrachate_stats"
    end
  end

  resources :pick_user_games

  resources :pick_users

  resources :pick_survivor_weeks

  resources :picks do
	  collection do
		  get 'close_pick'
	  end
  end

  resources :survivor_week_survivors

  resources :survivor_games

  resources :survivor_users

  resources :survivor_week_games do
  	collection do
  		get 'close_games'
  		get '/get_games',to: "survivor_week_games#get_games"
		get '/get_weeks',to: "survivor_week_games#get_weeks"
      get 'can_close/:id', to: "survivor_week_games#can_close"
  	end
  end

  resources :survivors do
    collection do
      put 'close'
  	end
  end

  resources :error_reports

  devise_for :users,  controllers: { registrations: "registrations"  }
  resources :questions

  resources :quiniela_users do
  	collection do
  		get 'winners'
  		get '/today_sales',to: "quiniela_users#today_sales"
  		get '/sales_by_month',to: "quiniela_users#sales_by_month"
  	end
  end

  resources :quiniela_questions

	resources :quinielas do
		collection do
			get 'last_quinielas', to: "quinielas#last_quinielas"
			get 'get_quinielas', to: "quinielas#get_quinielas"
			get 'close_quiniela'
			get 'toclose', to: "quinielas#toclose"
			get 'get_quinielas_no_winner', to: "quinielas#get_quinielas_no_winner"
			post 'buy_random_quinielas', to: "quinielas#buy_random_quinielas"
			get "/quiniela_details/:quiniela_id", to: "quinielas#quiniela_details"
			post "save_result", to: "quinielas#save_result"
		end
	end

    resources :games do
        collection do
			get '/future_games_programed', to: "games#future_games_programed"
            get 'next_game'
            get 'future_games'
            get 'finish_games'
            get 'today_games'
            get 'today_games_view'
            get '/lottery_name/:id', to: "games#lottery_name"
            get 'games_by_category'
        end
    end

    constraints subdomain: :webhooks do
        post '/:integration_name' => 'webhooks#receive', as: :receive_webhooks
    end

    resources :partials  do
        collection do
            get "check_gift_card", to: "partials#check_gift_card"
            get "gift_card"
            get "my_enrachate_create/:id", to: "partials#my_enrachate_create"
            get "lottery_rules"
            get "answer_register", to: "partials#answer_register"
            get "my_enrachate_tickets", to: "partials#my_enrachate_tickets"
            get "my_enrachate_leagues", to: "partials#my_enrachate_leagues"
            get "enrachate_survivor_history/:id", to: "partials#enrachate_survivor_history"
            get "my_ticket_history", to: "partials#my_ticket_history"
            get "my_ticket_history_special", to: "partials#my_ticket_history_special"
            get "enrachates_survivor", to: "partials#enrachates_survivor"
            get "top_100_enrachate", to: "partials#top_100_enrachate"
            get "top_100_enrachate_special", to: "partials#top_100_enrachate_special"
            get "tira_banner"
            get "enrachate_history", to: "partials#enrachate_history"
            get "enrachate_history_special", to: "partials#enrachate_history_special"
            get "enrachate_survivor/:id", to: "partials#enrachate_survivor"
            get "enrachate", to: "partials#enrachate"
            get "enrachate_special", to: "partials#enrachate_special"
            get "tiras_rules"
            get "_bank_tranfer"
            get "pay_in_store"
            get "pay_methods"
            post "change_score", to: "partials#change_score"
            post "change_pick_team", to: "partials#change_pick_team"
            get "select_pick_1/:id", to: "partials#select_pick_1"
            get 'tiras', to: "partials#tiras"
            get "pay_store", to: "partials#pay_store"
            get 'survivor_rules'
            get 'pickem_rules'
            get 'pickem_week_games_history/:id', to: 'partials#pickem_week_games_history'
			      get 'pickem_game'
            get "select_week_1/:id", to: "partials#select_week_1"
            get 'games_result'
            get 'response_access_pick/:id_request/:id_owner/:survivor/:response', to: "partials#response_access_pick"
            get 'response_request/:id_request/:id_owner/:survivor/:response', to: "partials#response_request"
			      get 'pickem_leagues', to: "partials#pickem_leagues"
            get 'pick_history/:id', to: "partials#pick_history"
            get 'get_weeks', to: "partials#get_weeks"
			      get 'pickem/:id', to: "partials#pickem"
			      post "invite_survivor", to: "partials#invite_survivor"
            post "invite_pick", to: "partials#invite_pick"
			      match "/inviting" => "partials#inviting", :via => :post
			      get 'invite_friends_survivor/:id', to: "partials#invite_friends_survivor"
            get 'invite_friends_pick/:id', to: "partials#invite_friends_pick"
			      get 'access_mail', to: "partials#access_request_mail"
            get 'access_mail_pick', to: "partials#access_request_mail_pick"
			      get 'my_leagues', to: "partials#my_leagues"
			      get 'my_pickem_leagues', to: "partials#my_pickem_leagues"
			      get 'next_game'
			      get 'finish_games'
			      get 'future_games'
			      get 'set_survivor_page/:id', to: "partials#set_survivor_page"
			      get 'survivor_history/:id', to: "partials#survivor_history"
			      get 'survivor_game'
			      get 'survivor_search', to: "partials#set_survivor_page"
      			get 'survivor_leagues', to: "partials#survivor_leagues"
      			get "/current_survivors", to: "partials#get_survivor"
      			get "/team_logos/:id", to: "partials#team_logos"
      			post 'buy_random_quinielas', to: "partials#buy_random_quinielas"
      			get 'get_quinielas_no_winner', to: "partials#get_quinielas_no_winner"
            post "credit_card_form", to: "partials#credit_card_pay"
            post "pay_methods", to: "partials#credit_card_pay"
            get "/partials/:user", to: "partials#get_customer_credit_cars"
            get "complete_buy"
            get "buy_error"
      			get "tickets_history"
      			get "client_details"
            post "delete_ticket", to: 'partials#delete_ticket'
            get 'lottery', to: "partials#lottery"
            get 'get_quinielas_mainpage', to: "partials#get_quinielas_mainpage"
    		    get "/lotteries/:id", to: "partials#lotteries"
    		    get "/quinielas/:id", to: "partials#quinielas"
    			  get "invite"
            get "/history", to: "partials#history"
            get "checkout"
            match "/checkout" => "partials#dispersion", :via => :post
            match "/credit_card_form/delete_card/:card/:customer" => "partials#delete_card", :via => :post
			      post 'buy_much_tickets', to: "partials#buy_much_tickets"
        end
    end

  resources :teams
  resources :sport_categories

	resources :categories do
		collection do

		end
	end

  resources :users do
      collection do
      get "day_activity"
      get "activity_of_day/:date" , to: "users#activity_of_day"
      get "/lotteries/:id", to: "users#lotteries"
		  get "/quinielas/:id", to: "users#quinielas"
		  get "send_mails"
      get "tickets_history"
		  match "/update_reference" => "users#search_reference", :via => :post
		  get "/client_details/:id_client", to: "users#client_details"
		  post "/send_mails_all", to: "users#send_mails_all"
      end
  end

  resources :user_lotteries do
    collection do
        get 'winners'
        get 'winners_total'
		get '/today_sales',to: "user_lotteries#today_sales"
        get 'winners_view'
		get "tickets_by_lottery"
		get "/tickets", to: "user_lotteries#search_ticket_by_lottery"
		get '/sales_by_month',to: "user_lotteries#sales_by_month"
    end
  end

  resources :lotteries do
        collection do
           get "/team_logos/:id", to: "lotteries#team_logos"
			get "/all_lotteries", to: "lotteries#all_lotteries"
			get 'last_lotteries', to: "lotteries#last_lotteries"
      end
    end

  resources :sports

  resources :roles

  get 'welcome/index'
  get 'welcome/index_client'
  get 'language/i18n/:locale' => 'language#i18n'
  get 'partials/credit_card_form'
  get 'welcome/terms', to: "welcome#no_sign_in"
  get 'welcome/about', to: "welcome#ho_we_are"
  get 'welcome/contact', to: "welcome#contact"
  get 'welcome/privacy', to: "welcome#privacy"
  get 'welcome/faq', to: "welcome#faq"
  post "/webhooks", to: "webhooks#receive"
  post "/", to: "webhooks#receive"

  get '/landing', :to => redirect('/index2.html')
  get '/error', :to => redirect('/404.html')

	  root 'welcome#index'

end

app/models/gift_card.rb
class GiftCard < ActiveRecord::Base
  belongs_to :user
  validates :code, uniqueness: true
  
end

app/controllers/gift_cards_controller.rb
class GiftCardsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_gift_card, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @gift_cards = GiftCard.all
    respond_with(@gift_cards)
  end


  def generate_massive_cards
    array_codes = []
    for i in 1..params[:quantity].to_i
      code = SecureRandom.hex(5).upcase
      array_codes.push(code)
      value = params[:value]
      GiftCard.create({:value => value, :code => code, :available => true})
    end
    BuyMailer.generate_card_codes(array_codes, params[:value]).deliver
    render json: true
  end

  def show
    respond_with(@gift_card)
  end

  def new
    @gift_card = GiftCard.new
    respond_with(@gift_card)
  end

  def edit
  end

  def create
    @gift_card = GiftCard.new(gift_card_params)
    @gift_card.save
    respond_with(@gift_card)
  end

  def update
    @gift_card.update(gift_card_params)
    respond_with(@gift_card)
  end

  def destroy
    @gift_card.destroy
    respond_with(@gift_card)
  end

  private
    def set_gift_card
      @gift_card = GiftCard.find(params[:id])
    end

    def gift_card_params
      params.require(:gift_card).permit(:value, :user_id, :code, :available)
    end
end

app/views/gift_cards/_form.html.erb
<%= form_for(@gift_card, :html => { :class => "form-horizontal" }) do |f| %>
<% if @gift_card.errors.any? %>
<div id="error_explanation">
  <% if @gift_card.errors.count == 1 %>
  <h5><%= t("activerecord.errors.template.header.one", model: t("activerecord.models.gift_card")) %></h5>
  <% else %>
  <h5><%= t("activerecord.errors.template.header.other", model: t("activerecord.models.gift_card"), :count => @gift_card.errors.count) %></h5>
  <% end %>
  <ul>
    <% @gift_card.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<!-- begin col-md-6 -->
<div class="col-md-6">

  <div class="form-group">
<%= f.label :value, :class => "col-md-3" %>
<div class="col-md-9">
<%= f.text_field :value, :class => "form-control", :required => "required" %>
</div>
</div>

<div class="form-group">
<%= f.label :code, :class => "col-md-3" %>
<div class="col-md-9">
<%= f.text_field :code, :class => "form-control", :required => "required" %>
</div>
</div>

</div>

<div class="col-md-6">

                  <div class="form-group">
          <%= f.label :user_id, :class => "col-md-3" %>
          <div class="col-md-9">
            <%= f.collection_select(:user_id, User.all, :id, :select_display, { :include_blank => false, :prompt => true },  :class => "form-control") %>
          </div>
        </div>

                  <div class="form-group">
          <%= f.label :available, :class => "col-md-3" %>
          <div class="col-md-9">
            <%= f.check_box :available, :class => "form-control" %>
          </div>
        </div>
      </div>
<!-- end col-md-6 -->

<div class="col-md-12">
  <div class="form-group">
    <div class="col-md-12 text-center">
      <%= f.button :class => "submit btn btn-success", :data => { :disable_with => t("actions.saving") } do %>
      <i class='icon-ok'></i>
      <%= t("actions.save") %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/gift_cards/create_massive.html.erb
<div class="row">
  <br>
  <h4 style="text-align:center; font-size:20px; color:black;">Creacion masiva de tarjetas</h4>
  <hr>
  <div class="col-md-6 col-xs-12">
    <h4 style="text-align:center; color:black;">Selecciona la cantidad de tarjetas a crear:</h4>
      <input id="quantity_cards" type="number" oninput="maxLengthCheck(this)" style="text-align:center; font-weight:800; color:black;" max="1000" maxlength = "3" class="input input-lg form-control" name="" value="">
  </div>
  <div class="col-md-6 col-xs-12">
    <h4 style="text-align:center; color:black;">Selecciona el valor nominal de las tarjetas:</h4>
    <input id="value_cards" type="number" oninput="maxLengthCheck(this)" style="text-align:center; font-weight:800; color:black;" max="1000" maxlength = "3" class="input input-lg form-control" name="" value="">
  </div>
  <div class="clearfix"></div>
  <hr>
  <div class="col-md-12 col-xs-12" id="generated_codes">

  </div>
<h4 style="text-align:center"><button type="button" id="generate_cards" class="btn btn-lg btn-primary" name="button">Generar tarjetas de regalo</button></h4>
</div>



<div id="response_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header" style="color:white; background-color:#2d68ac;">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 style="text-align:center" class="modal-title">Canjeo de tarjeta de regalo</h4>
      </div>
      <div class="modal-body">
        <p style="color:black; font-weight:800; text-align:center;" id="text_response"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>

  </div>
</div>


<script type="text/javascript">
    $("#generate_cards").click(function(){
      $.ajax({
method: "GET",
url: "/gift_cards/generate_massive_cards",
data: { value: $("#value_cards").val(), quantity: $("#quantity_cards").val()}
}).done(function( msg ) {
if(msg == true){
    $("#text_response").text("Las tarjetas se generaron con exito")
    $("#response_modal").modal("show");
    setTimeout(function(){ window.location.assign("/gift_cards"); }, 4000);
}else{
  if(msg === 0){
    $("#text_response").text("Hubo un error en la generacion");
    $("#response_modal").modal("show");
  }else{
        $("#text_response").text("La generacion tuvo un error.");
      $("#response_modal").modal("show");
}
}

});
    })
</script>


<script>
  // This is an old version, for a more recent version look at
  // https://jsfiddle.net/DRSDavidSoft/zb4ft1qq/2/
  function maxLengthCheck(object)
  {
    if (object.value.length > object.maxLength)
      object.value = object.value.slice(0, object.maxLength)
  }
</script>

app/views/gift_cards/edit.html.erb
<div class="row">
  <!-- begin col-12 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <h3 style="margin-left:15px"><%= t("actions.edit_title_male", model: t("activerecord.models.gift_card").downcase) %></h3>
        </div>
      </div>
      <div class="panel-body">
        <%= render "form" %>
      </div>
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-12 -->
</div>
<!-- end row -->

<!-- begin row -->
<div class="row">
  <div class="col-md-12">
    <% if can? :delete, @gift_card %>
      <%= link_to @gift_card, method: :delete, data: { confirm: t("are_you_sure?", model: t("activerecord.models.gift_card").downcase) }, :class => "btn btn-danger" do %>
        <i class="icon-trash"></i>
        <%= t("actions.delete") %>
      <% end %>
    <% end %>
    <% if can? :index, GiftCard  %>
      <%= link_to gift_cards_path, :class => "btn btn-default" do %>
        <i class='icon-chevron-left'></i>
        <%= t("actions.back") %>
      <% end %>
    <% end %>
  </div>
  <!-- end col-12 -->
</div>
<!-- end row -->

app/views/gift_cards/index.html.erb
<div class="row">
  <!-- begin col-12 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <h3 style="margin-left:15px"><%= t("activerecord.models.gift_cards") %></h3>
        </div>
      </div>
      <div class="panel-body">
        <div class="table-responsive">
          <table id="data-table" class="table table-bordered table-hover table-striped nowrap" width="100%">
            <thead>
              <tr>
                                  <th><%= t("activerecord.attributes.gift_card.value") %></th>
                                  <th><%= t("activerecord.attributes.gift_card.user") %></th>
                                  <th><%= t("activerecord.attributes.gift_card.code") %></th>
                                  <th><%= t("activerecord.attributes.gift_card.available") %></th>
                                  <th>Fecha canje:</th>
                                <th style="width: 155px"></th>
              </tr>
            </thead>

            <tbody>
              <% @gift_cards.each do |gift_card| %>
              <tr>
                                  <td><%= gift_card.value %></td>
                                  <td><%= gift_card.user ? gift_card.user.select_display : "Aun no esta canjeada" %></td>
                                  <td><%= gift_card.code %></td>
                                  <td><%= gift_card.available %></td>
                                  <td><%= gift_card.available == false ? gift_card.updated_at : "No se a canjeado"  %></td>
                                <td class="action-link">
                  <% if can? :show,gift_card %>
                    <%= link_to gift_card, :class => "btn btn-default", :title => t("actions.show") do %>
                      <i class="fa fa-eye"></i>
                    <% end %>
                  <% end %>
                  <% if can? :edit, gift_card %>
                    <%= link_to edit_gift_card_path(gift_card), :class => "btn btn-info", :title => t("actions.edit") do %>
                      <i class="fa fa-pencil"></i>
                    <% end %>
                  <% end %>
                  <% if can? :delete, gift_card %>
                    <%= link_to gift_card, :method => :delete, :data => { :confirm => t("are_you_sure?", model: t("activerecord.models.gift_card").downcase) }, :class => "btn btn-danger", :title => t("actions.delete") do %>
                      <i class="fa fa-trash"></i>
                    <% end %>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="text-center">

        </div>
      </div>
      <!-- end panel-body -->
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-12 -->
</div>
<!-- end row -->

<!-- begin row -->
<div class="row">
  <div class="col-md-12">
    <% if can? :new, GiftCard  %>
      <%= link_to new_gift_card_path, :class => "btn btn-default" do %>
        <i class="icon-plus-sign-alt"></i>
        <%= t("actions.new") %>
      <% end %>
    <% end %>
  </div>
  <!-- end col-12 -->
</div>
<!-- end row -->
<script>
       var current_language = $("#current_language").val();
       var languaje;

    if(current_language == "en"){
    languaje= "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/English.json"
}else{
    languaje = "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
}

$('#data-table').DataTable({
    responsive: true,
    order: [0,"desc"],
     "language": {
            "url": languaje
        }
});
</script>

app/views/gift_cards/new.html.erb
<div class="row">
  <!-- begin col-12 -->
  <div class="col-md-12">
    <!-- begin panel -->
    <div class="panel panel-primary">
      <div class="panel-heading">
        <div class="row">
          <h3 style="margin-left:15px"><%= t("actions.new_title_male", model: t("activerecord.models.gift_card").downcase) %></h3>
        </div>
      </div>
      <div class="panel-body">
        <%= render "form" %>
      </div>
    </div>
    <!-- end panel -->
  </div>
  <!-- end col-12 -->
</div>
<!-- end row -->

<!-- begin row -->
<div class="row">
  <div class="col-md-12">
    <% if can? :index, GiftCard  %>
      <%= link_to gift_cards_path, :class => "btn btn-default" do %>
        <i class='icon-chevron-left'></i>
        <%= t("actions.back") %>
      <% end %>
    <% end %>
  </div>
  <!-- end col-12 -->
</div>
<!-- end row -->

app/views/gift_cards/show.html.erb
<!-- begin row -->
<div class="row">
  <!-- begin col-md-12 -->
  <div class="col-md-12">
    <div class="invoice">
      <div class="invoice-content">
        <div class="table-responsive">
          <table class="table table-invoice">
            <thead>
              <tr>
                <td colspan="2">
                  <h4><%= t("details_of", model: t("activerecord.models.gift_card").downcase) %></h4>
                </td>
              </tr>
            </thead>
            <tbody>
                              <tr>
                  <td>
                    <%= t("activerecord.attributes.gift_card.value") %>: <br />
                    <small><%= @gift_card.value %></small>
                  </td>
                </tr>
                              <tr>
                  <td>
                    <%= t("activerecord.attributes.gift_card.user") %>: <br />
                    <small><%= @gift_card.user %></small>
                  </td>
                </tr>
                              <tr>
                  <td>
                    <%= t("activerecord.attributes.gift_card.code") %>: <br />
                    <small><%= @gift_card.code %></small>
                  </td>
                </tr>
                              <tr>
                  <td>
                    <%= t("activerecord.attributes.gift_card.available") %>: <br />
                    <small><%= @gift_card.available %></small>
                  </td>
                </tr>
                              <tr>
                  <td>
                    <%= t("activerecord.attributes.gift_card.created_at") %>: <br />
                    <small><%= @gift_card.created_at %></small>
                  </td>
                </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="invoice-footer text-muted"></div>
    </div>
  </div>
  <!-- end col-md-12 -->
</div>
<!-- end row -->

<!-- begin row -->
<div class="row">
  <div class="col-md-12">
    <% if can? :edit, @gift_card %>
      <%= link_to edit_gift_card_path(@gift_card), :class => "btn btn-default" do %>
        <i class="icon-pencil"></i>
        <%= t("actions.edit") %>
      <% end %>
    <% end %>
    <% if can? :delete, @gift_card %>
      <%= link_to @gift_card, method: :delete, data: { confirm: t("are_you_sure?", model: t("activerecord.models.gift_card").downcase) }, :class => "btn btn-danger" do %>
        <i class="icon-trash"></i>
        <%= t("actions.delete") %>
      <% end %>
    <% end %>
    <% if can? :index, GiftCard  %>
      <%= link_to gift_cards_path, :class => "btn btn-default" do %>
        <i class="icon-chevron-left"></i>
        <%= t("actions.back") %>
      <% end %>
    <% end %>
  </div>
  <!-- end col-12 -->
</div>
<!-- end row -->